### ISSUE TITLE
Split package into multiple and make this a Meta package

### ISSUE THREAD

**Issue by Evizero** [JuliaML/MLDataUtils.jl#29]
This package has come a long way, but at the moment it feels a bit like the package equivalent of a [blob design](http://antipatterns.com/briefing/sld024.htm). I am very happy with `MLLabelUtils` because it is a single concern kinda package, which makes it easier (and more fun) to design and flesh out.

I think it would make sense to make this package a convenience collection package that reexports data related ML packages.

- [x] `MLDataPattern.jl` ([done](https://github.com/JuliaML/MLDataPattern.jl)). Only deals with the data access pattern, which are currently the dominating part of this package.

- [x] `MLDatasets.jl`. Self explanatory.

- [x] `MLLabelUtils.jl`. All things concerning classification labels.

- [ ] `MLDataGenerators.jl` (doesn't exist yet). Move artifical data generators there. Also absorb #9 

- [ ] `MLPreprocessing.jl` ([in progress](https://github.com/JuliaML/MLPreprocessing.jl)). This aspect is a bit neglected so far.

Last but not least it could offer some glue code. For example if MLDataUtils is the meta package it could define the needed interface for `DataFrame` and friends, so they just work out of the box.

**Comment by Evizero** [comment]
parts of the current documentation should probably be moved to the JuliaML website instead

**Comment by Evizero** [comment]
As a side note, I will remove precompilation from MLDataUtils, once the code move to MLDataPattern is complete. This is because I will add a `Requires.jl` dependency here, so that we can have default support for all kinds of different data sources, such as `DataFrame` and `DataTable`
